### ISSUE TITLE
May make more sense to import the BackendEntrypoint directly

### ISSUE THREAD

**Issue by steven-eratos** [eratosio/eratos-xarray#6]
**Is your feature request related to a problem? Please describe.**
Currently it is not clear what `import eratos_xarray` actually does in the code. If a user forgets to import it, it will obviously fail with an error as `xarray` is unable to find the `eratos` engine. However when working in Jupyter Notebooks I found that if I try to import `eratos_xarray` after already calling `xr.open_dataset` it will still fail. This is because `xarray` internally caches all engines once it tries to open a dataset, and importing `eratos_xarray` does not actually update this list. However if we import the `EratosBackendEntrypoint` directly it works.

The following code reproduces the issue - 

```python
import xarray as xr
from eratos.creds import AccessTokenCreds
import os
eratos_id = os.environ['ERATOS_KEY']
eratos_secret = os.environ['ERATOS_SECRET']

ecreds = AccessTokenCreds(
  eratos_id,
  eratos_secret)

ern = "ern:e-pn.io:resource:eratos.blocks.silo.maxtemperature"
# does not work
print("Trying with no import")
try:
    ds = xr.open_dataset(ern, engine='eratos', eratos_auth=ecreds)
except Exception as e:
    print(e)

import eratos_xarray
print("Trying with eratos_xarray imported")
# does not work
try:
    ds = xr.open_dataset(ern, engine='eratos', eratos_auth=ecreds)
except Exception as e:
    print(e)

print("Trying with engine class")
from eratos_xarray.backend.eratos_ import EratosBackendEntrypoint
ds = xr.open_dataset(ern, engine=EratosBackendEntrypoint, eratos_auth=ecreds)
print(ds)
```

**Describe the solution you'd like**
We should recommend people to import `EratosBackendEntrypoint` (perhaps make edits to the `__init__.py` and add an `__init__.py` to `backend` so it can be imported directly). It makes it a bit more clear what `eratos_xarray` actually does and avoids the obscure issue I had above.

**Comment by joeratos** [comment]
Importing the backend via import without specifying the engine is a pretty common pattern however I do think the documentation could be clearer. 

see `rasterio` for example
https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
https://corteva.github.io/rioxarray/stable/examples/reproject.html

I think a better alternative might be to support also support an explicit alternative such as `eratos_xarray.open_dataset(...)` if that is preferred

e.g.
```
import eratos_xarray # for the extension to load
import xarray as xr
ern = ...
creds = ... etc
eratos_xarray.open_dataset(ern, eratos_auth=creds) #   for a more explicit implementation
xr.open_dataset(ern, eratos_auth=creds) #  identical to line above with backend loaded
```

**Comment by steven-eratos** [comment]
From the [xarray documentation](https://docs.xarray.dev/en/latest/internals/how-to-add-new-backend.html#rst-backend-registration) it also seems that you can 'register' the backend by adding a couple lines in the build file.
```
[tool.poetry.plugins."xarray.backends"]
eratos = "eratos_xarray.backend.eratos_:EratosBackendEntrypoint"
```
This makes it so that the `eratos` backend is always available even without the `import eratos_xarray` line. Perhaps this is another solution?

**Comment by aidanjgriffiths** [comment]
@steven-eratos, if you can demonstrate the use of the `EratosBackendEntrypoint` and it improves the user experience I could review the PR. Judging by [this guide](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html) it doesn't seem too involved. I think having `eratos` as a listed backend once you install it seems like a good outcome and would be what I would expect the behaviour of a plugin package.

EDIT: You can start using the above in personal projects or packages, I think having more options is always a good thing but whether we want to change the docs/suggested method is more of a consensus/team decision.

**Comment by steven-eratos** [comment]
@aidanjgriffiths , I've made a PR to add the feature in #9

**Comment by aidanjgriffiths** [comment]
Closing due to #9 being merged to `master`
